baseurl         = "https://intensywna.com"
theme           = "casper-two"
languageCode    = "pl"
disqusShortname = ""
paginate        = 6
SectionPagesMenu = "main"
defaultContentLanguage: "pl"

languages:
  pl:
    weight: 1
    languageName: "Polish"

[params]
  title       = "Intensywna PL"
  subtitle    = "Nowości w intensywnej terapii i medycynie okołooperacyjnej"

  cover       = "img/blog-cover.jpg"
  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "IntensywnaPL"
  fbName = "IntensywnaPL"
  #githubName = "eueung"

  logo = "/photos/intPL.png"
  orgName = "@IntensywnaPL"
  orgWebsite = "https://intensywna.com"
  orgDescription = "Intensywnie o intensywnej"

  #author = "@IntensywnaPL"
  #authorAvatar = "/photos/logasss.png"
  authorLocation = "Polska, Kraków"
  authorWebsite = "https://intensywna.com"
  authorDescription = "Intensywnie o intensywnej"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Strona główna"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Posty"
  url = "/tags/post/"
  weight = 100

[[menu.main]]
  name = "Artykuły"
  url = "/categories/artykuł/"
  weight = 99

[[menu.main]]
  name = "Mp.pl"
  url = "https://www.mp.pl/oit/"
  weight = 95